version: 2
updates:
  - package-ecosystem: gradle
    directory: "/backend"
    schedule:
      interval: weekly
  
  - package-ecosystem: gradle
    directory: "/android"
    schedule:
      interval: weekly
      
  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: weekly
    groups:
      eslint:
        patterns:
          - "*eslint*"  
    open-pull-requests-limit: 10
